AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1

# Enable extensions
require:
  - rubocop-performance
  - rubocop-rails

# Rules for OAuth
Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
